"""Figures, tables and number macros for the R-Super MedFormer / PanTS report.

Every number in report.tex is written here from files produced by the benchmark
scripts; nothing is typed into the LaTeX by hand.

Inputs
    outputs/eval/pants/medformer/          per-case results of MedFormer (evaluate_models.py)
    outputs/eval/pants/totalseg/           per-case results of TotalSegmentator (reference comparator)
    outputs/eval/pants/report/             macro / pooled / presence / compare / ranking / cohorts (benchmark_report.py)
    generated/audit_pants_test.csv         `segevalkit audit` of the PanTS test labels
    patched_cases.txt                      the 25 cases that needed the upstream padding fix

    python reports/rsuper_medformer/make_report.py      # then: tectonic -X compile report.tex
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

import segevalkit as sek  # noqa: E402
from segevalkit import plotting as P  # noqa: E402
from segevalkit.cohort import cohort_summary  # noqa: E402
from segevalkit.plotting.theme import CATEGORICAL, ERROR_COLORS, INK, PURPLE, theme  # noqa: E402
from segevalkit.stats import presence_detection  # noqa: E402

HERE = Path(__file__).resolve().parent
STORE = Path("/l/users/abhijit.das/SegEvalKit")
EVAL = STORE / "outputs/eval/pants"
REPORT = EVAL / "report"
GEN, FIG = HERE / "generated", HERE / "figures"
MF, TS = "MedFormer", "TotalSegmentator"

NAME = {"pancreas": "Pancreas", "pancreatic_lesion": "Pancreatic lesion", "liver": "Liver", "spleen": "Spleen",
        "kidney_left": "Kidney (left)", "kidney_right": "Kidney (right)", "stomach": "Stomach",
        "gall_bladder": "Gallbladder", "duodenum": "Duodenum", "colon": "Colon",
        "adrenal_gland_left": "Adrenal (left)", "adrenal_gland_right": "Adrenal (right)", "aorta": "Aorta",
        "postcava": "Inferior vena cava", "superior_mesenteric_artery": "Sup. mesenteric artery",
        "veins": "Veins", "common_bile_duct": "Common bile duct"}
ORGANS10 = ["pancreas", "liver", "spleen", "kidney_left", "kidney_right", "stomach", "gall_bladder", "duodenum",
            "aorta", "postcava"]

macros: list[str] = []


def cmd(name: str, value) -> None:
    macros.append(f"\\newcommand{{\\{name}}}{{{value}}}")


def f3(v) -> str:
    """Score with three decimals ('.864'); '--' for missing."""
    if v is None or not np.isfinite(v):
        return "--"
    return "1.000" if v >= 0.9995 else f"{v:.3f}".replace("0.", ".", 1) if v >= 0 else f"{v:.3f}"


def f1(v) -> str:
    return "--" if v is None or not np.isfinite(v) else f"{v:.1f}"


def pct(v) -> str:
    return f"{100 * v:.0f}"


def tex_group(g: str) -> str:
    return (g.replace("%", "\\%").replace("–", "--").replace("≤ ", "$\\le$\\,").replace("> ", "$>$\\,")
            .replace("< ", "$<$\\,"))


def ptex(p) -> str:
    if not np.isfinite(p):
        return "--"
    return "$<\\!10^{-3}$" if p < 1e-3 else f"{p:.3f}"


def retitle(ax, text: str) -> None:
    """Replace the library's left-aligned title (and clear any centred one)."""
    ax.set_title("", loc="center")
    ax.set_title(text, loc="left")


def save(fig, name: str) -> None:
    fig.savefig(FIG / f"{name}.pdf")
    plt.close(fig)
    print("figure", name)


def table(name: str, colspec: str, header: str, rows: list[str], note: str = "") -> None:
    body = "\n".join(rows)
    tail = f"\\multicolumn{{{colspec.count('l') + colspec.count('r') + colspec.count('c')}}}{{l}}{{\\footnotesize {note}}}\\\\\n" if note else ""
    (GEN / f"{name}.tex").write_text(
        f"% generated by make_report.py\n\\begin{{tabular}}{{{colspec}}}\n\\toprule\n{header} \\\\\n\\midrule\n"
        f"{body}\n\\bottomrule\n{tail}\\end{{tabular}}\n")


def main() -> None:
    GEN.mkdir(exist_ok=True)
    FIG.mkdir(exist_ok=True)
    mf = sek.load_results(EVAL / "medformer")
    ts = sek.load_results(EVAL / "totalseg")
    mf.meta["name"], ts.meta["name"] = MF, TS
    wide = mf.wide()
    tsw = ts.wide()
    macro = pd.read_csv(REPORT / "macro.csv")
    pooled = pd.read_csv(REPORT / "pooled.csv")
    pres = pd.read_csv(REPORT / "presence.csv").set_index("model")
    comp = pd.read_csv(REPORT / f"compare_{MF}_vs_{TS}.csv")
    rank = pd.read_csv(REPORT / "ranking.csv")
    coh = pd.read_csv(REPORT / "cohorts_MedFormer.csv")
    coht = pd.read_csv(REPORT / "cohort_tests_MedFormer.csv")
    numbers = json.loads((REPORT / "numbers.json").read_text())
    meta = json.loads((EVAL / "medformer/meta.json").read_text())
    audit = pd.read_csv(GEN / "audit_pants_test.csv")
    patched = [l.split(",") for l in (HERE / "patched_cases.txt").read_text().splitlines() if l.startswith("PanTS")]

    # ---------------------------------------------------------------- provenance
    cmd("nCases", numbers["n_cases"][MF])
    cmd("nCasesTS", numbers["n_cases"][TS])
    cmd("nStructures", wide["label"].nunique())
    cmd("sekVersion", meta["segevalkit_version"])
    cmd("evalDate", meta["created"][:10])
    cmd("nsdTol", f"{meta['config']['params']['nsd']['tolerance_mm']:g}")
    cmd("minLesionVox", meta["config"]["min_lesion_voxels"])
    cmd("connectivity", meta["config"]["connectivity"])
    rsuper = subprocess.run(["git", "-C", str(STORE / "third_party/R-Super"), "log", "-1", "--format=%h|%cs"],
                            capture_output=True, text=True).stdout.strip().split("|")
    cmd("rsuperCommit", rsuper[0])
    cmd("rsuperDate", rsuper[1])
    cmd("nPatched", len(patched))
    cmd("nPatchedZ", sum(int(p[1]) in (129, 130) for p in patched))
    cmd("nPatchedX", sum(int(p[3]) in (129, 130) for p in patched))
    cmd("nAuditCases", audit["case_id"].nunique())
    cmd("nAuditFiles", len(audit))
    cmd("nAuditAorta", int((audit["structure"] == "aorta").sum()))
    cmd("auditSameShape", "all" if audit["same_shape"].all() else "not all")

    # ---------------------------------------------------------------- per-structure table
    mm = macro[macro.model == MF].set_index(["label", "metric"])
    order = [s for s in NAME if s in set(wide["label"])]
    rows = []
    for s in order:
        cells = []
        for m, fmt in (("dice", f3), ("nsd", f3), ("hd95", f1)):
            r = mm.loc[(s, m)]
            cells += [f"{fmt(r['mean'])} {{\\scriptsize [{fmt(r.ci_low)}, {fmt(r.ci_high)}]}}", fmt(r["median"])]
        rows.append(f"{NAME[s]} & " + " & ".join(cells) + " \\\\")
    table("t_structures", "lrrrrrr",
          " & \\multicolumn{2}{c}{Dice $\\uparrow$} & \\multicolumn{2}{c}{NSD (\\nsdTol\\,mm) $\\uparrow$} & "
          "\\multicolumn{2}{c}{HD95 (mm) $\\downarrow$} \\\\\n & mean [95\\% CI] & median & mean [95\\% CI] & median & "
          "mean [95\\% CI] & median", rows)
    for s, k in (("pancreas", "Panc"), ("liver", "Liver"), ("spleen", "Spleen"), ("kidney_left", "KidL"),
                 ("duodenum", "Duod"), ("pancreatic_lesion", "Les"), ("common_bile_duct", "CBD")):
        for m, key in (("dice", "Dice"), ("nsd", "NSD")):
            cmd(f"mf{k}{key}", f3(mm.loc[(s, m), "mean"]))
            cmd(f"mf{k}{key}Med", f3(mm.loc[(s, m), "median"]))
        cmd(f"mf{k}HD", f1(mm.loc[(s, "hd95"), "mean"]))
        cmd(f"mf{k}HDMed", f1(mm.loc[(s, "hd95"), "median"]))
    organ_means = [mm.loc[(s, "dice"), "mean"] for s in order if s != "pancreatic_lesion"]
    cmd("mfNOrgansAbove", sum(v >= 0.85 for v in organ_means))
    cmd("mfNOrgans", len(organ_means))

    # ---------------------------------------------------------------- macro vs pooled
    pl = pooled[pooled.model == MF].set_index(["label", "metric"])
    rows = []
    for s in order:
        if s == "pancreatic_lesion":
            continue
        pd_, pp, pr = (pl.loc[(s, k), "value"] for k in ("pooled_dice", "pooled_precision", "pooled_recall"))
        rows.append(f"{NAME[s]} & {f3(mm.loc[(s, 'dice'), 'mean'])} & {f3(pd_)} & {f3(pp)} & {f3(pr)} \\\\")
    table("t_levels", "lrrrr", "Structure & macro Dice & pooled Dice & pooled precision & pooled recall", rows)
    cmd("mfGallMacro", f3(mm.loc[("gall_bladder", "dice"), "mean"]))
    cmd("mfGallPooled", f3(pl.loc[("gall_bladder", "pooled_dice"), "value"]))
    cmd("mfPancPooled", f3(pl.loc[("pancreas", "pooled_dice"), "value"]))

    # ---------------------------------------------------------------- lesions
    les = mf.lesions
    lref = les[(les.kind == "ref") & (les.label == "pancreatic_lesion")]
    cmd("nRefLesions", len(lref))
    cmd("nRefDetected", int(lref.detected.sum()))
    lw = wide[wide.label == "pancreatic_lesion"]
    pos, neg = lw[lw.ref_empty == 0], lw[lw.ref_empty == 1]
    cmd("mfLesDicePos", f3(pos.dice.mean()))
    cmd("mfLesDiceNeg", f3(neg.dice.mean()))
    cmd("mfNegNoPred", int((neg.pred_empty == 1).sum()))
    cmd("nPosPatients", len(pos))
    cmd("nNegPatients", len(neg))
    lp = pl.loc["pancreatic_lesion"]
    rows = []
    for k, lab in (("pooled_lesion_sensitivity", "Lesion sensitivity (found / real lesions)"),
                   ("pooled_lesion_precision", "Lesion precision (real / predicted lesions)"),
                   ("pooled_lesion_f1", "Lesion F1"),
                   ("fp_lesions_per_scan", "False-positive lesions per scan"),
                   ("pooled_dice", "Pooled lesion Dice (all tumour voxels)")):
        r = lp.loc[k]
        rows.append(f"{lab} & {r.value:.3f} & [{r.ci_low:.3f}, {r.ci_high:.3f}] \\\\")
        cmd({"pooled_lesion_sensitivity": "mfLesSens", "pooled_lesion_precision": "mfLesPrec",
             "pooled_lesion_f1": "mfLesFone", "fp_lesions_per_scan": "mfFPScan",
             "pooled_dice": "mfLesPooledDice"}[k], f"{r.value:.2f}")
    table("t_lesion", "lrr", "Test-set lesion metric & value & 95\\% CI", rows)
    p = pres.loc[MF]
    cmd("mfAUC", f"{p.auc:.3f}")
    cmd("mfSens", f"{p.sensitivity:.3f}")
    cmd("mfSpec", f"{p.specificity:.3f}")
    cmd("mfThr", f"{p.threshold:.2f}")
    per = [("lesion_recall", "Lesion sensitivity"), ("lesion_precision", "Lesion precision"),
           ("lesion_f1", "Lesion F1"), ("lesionwise_dice", "Lesion-wise Dice"),
           ("panoptic_quality", "Panoptic quality"), ("dice", "Dice of the tumour voxels"),
           ("false_positive_lesions", "False-positive lesions per scan")]
    rows = []
    for k, lab in per:
        v = pos[k].dropna()
        val = f"{v.mean():.2f}" if k == "false_positive_lesions" else f3(v.mean())
        rows.append(f"{lab} & {val} & {len(v)} \\\\")
    v = neg["false_positive_lesions"].dropna()
    rows.append(f"False-positive lesions per scan, tumour-free & {v.mean():.2f} & {len(v)} \\\\")
    cmd("mfNegFP", f"{v.mean():.2f}")
    cmd("mfPosLesRecall", f3(pos.lesion_recall.mean()))
    cmd("mfPosLesFone", f3(pos.lesion_f1.mean()))
    cmd("mfPosLesPrec", f3(pos.lesion_precision.mean()))
    table("t_lesion_case", "lrr", "Per tumour patient (mean) & value & patients", rows)
    # detection by size (the same bins as the figure)
    bins = [0, 0.1, 0.5, 1, 5, 20, np.inf]
    names = ["$<$\\,0.1", "0.1--0.5", "0.5--1", "1--5", "5--20", "$>$\\,20"]
    b = pd.cut(lref.volume_ml, bins=bins, labels=names, include_lowest=True)
    g = lref.groupby(b, observed=False)["detected"]
    rows = [f"{n} & {int(g.size()[n])} & {pct(g.mean()[n]) if g.size()[n] else '--'}\\% \\\\" for n in names]
    table("t_size", "lrr", "Lesion volume (mL) & lesions & detected", rows)
    small = lref[lref.volume_ml < 0.5]
    big = lref[lref.volume_ml >= 1]
    cmd("mfDetSmall", pct(small.detected.mean()))
    cmd("mfDetBig", pct(big.detected.mean()))
    cmd("nSmallLes", len(small))

    # calibration (lesion probabilities, band within 10 mm of either mask)
    rows = []
    for k, lab in (("ece", "Expected calibration error"), ("brier", "Brier score"), ("auprc", "Area under PR curve")):
        r = mm.loc[("pancreatic_lesion", k)]
        rows.append(f"{lab} & {r['mean']:.3f} & {r['median']:.3f} & {int(r.n)} \\\\")
        cmd({"ece": "mfECE", "brier": "mfBrier", "auprc": "mfAUPRC"}[k], f"{r['mean']:.3f}")
    table("t_calib", "lrrr", "Lesion probability metric & mean & median & patients", rows)

    # ---------------------------------------------------------------- paired comparison with TotalSegmentator
    tm = macro[macro.model == TS].set_index(["label", "metric"])
    rows = []
    for s in ORGANS10:
        cells = []
        for m in ("dice", "nsd", "hd95"):
            r = comp[(comp.label == s) & (comp.metric == m)].iloc[0]
            fmt = f1 if m == "hd95" else f3
            cells.append(f"{fmt(r.mean_a)} / {fmt(r.mean_b)} & {pct(r.frac_a_better)}\\%")
        rows.append(f"{NAME[s]} & " + " & ".join(cells) + " \\\\")
    table("t_compare", "lrrrrrr",
          " & \\multicolumn{2}{c}{Dice} & \\multicolumn{2}{c}{NSD} & \\multicolumn{2}{c}{HD95 (mm)} \\\\\n"
          "Structure & MF / TS & MF better & MF / TS & MF better & MF / TS & MF better", rows)
    cmd("nCompSig", int(comp.significant.sum()))
    cmd("nComp", len(comp))
    cmd("maxPadj", ptex(comp.p_adjusted.max()))
    d = comp[comp.metric == "dice"]
    cmd("fracDiceMin", pct(d.frac_a_better.min()))
    cmd("fracDiceMax", pct(d.frac_a_better.max()))
    cmd("fracSpleenDice", pct(d[d.label == "spleen"].frac_a_better.iloc[0]))
    cmd("tsSpleenDice", f3(tm.loc[("spleen", "dice"), "mean"]))
    cmd("tsSpleenHD", f1(tm.loc[("spleen", "hd95"), "mean"]))
    cmd("tsSpleenHDMed", f1(tm.loc[("spleen", "hd95"), "median"]))
    cmd("tsPancDice", f3(tm.loc[("pancreas", "dice"), "mean"]))
    h = comp[comp.metric == "hd95"]
    cmd("nHDmeanWorse", int((h.mean_a > h.mean_b).sum()))
    cmd("nHDmedBetterFrac", int((h.frac_a_better > 0.5).sum()))

    # ranking schemes
    rows, flips = [], []
    for s, dd in rank[rank.scheme != "bootstrap"].groupby("structure", sort=False):
        a = dd[dd.scheme == "aggregate-then-rank"].set_index("method")
        r_ = dd[dd.scheme == "rank-then-aggregate"].set_index("method")
        wa, wr = a["rank"].idxmin(), r_["rank"].idxmin()
        tau = rank[(rank.structure == s) & (rank.scheme == "bootstrap")].kendall_tau_median.iloc[0]
        rows.append(f"{NAME[s]} & {f3(a.loc[MF, 'mean'])} / {f3(a.loc[TS, 'mean'])} & {wa} & "
                    f"{r_.loc[MF, 'mean_rank']:.2f} / {r_.loc[TS, 'mean_rank']:.2f} & {wr} & {tau:.2f} \\\\")
        if wa != wr:
            flips.append(NAME[s].lower())
    table("t_ranking", "lrlrlr", "Structure & mean Dice MF / TS & winner & mean rank MF / TS & winner & "
          "bootstrap $\\tau$", rows)
    cmd("rankFlips", " and the ".join(flips) if flips else "none")
    cmd("nRankFlips", len(flips))

    # HD95 failure tail
    for s, k in (("spleen", "Spleen"), ("kidney_left", "KidL")):
        x = wide[wide.label == s]
        t = x[x.hd95 > 50]
        cmd(f"tail{k}N", len(t))
        cmd(f"tail{k}Share", pct(t.hd95.sum() / x.hd95.sum()))
        cmd(f"tail{k}RefEmpty", int(((t.ref_empty == 1) & (t.pred_empty == 0)).sum()))
        both = t[(t.ref_empty == 0) & (t.pred_empty == 0)]
        cmd(f"tail{k}Both", len(both))
        cmd(f"tail{k}BothDice", f3(both.dice.median()))
        cmd(f"tail{k}BothHD", f"{both.hd95.median():.0f}")
        y = tsw[tsw.label == s]
        cmd(f"tsTail{k}N", int((y.hd95 > 50).sum()))
        cmd(f"refEmpty{k}", int(x.ref_empty.sum()))
        cmd(f"mfPredOnEmpty{k}", int(((x.ref_empty == 1) & (x.pred_empty == 0)).sum()))
        cmd(f"tsPredOnEmpty{k}", int(((y.ref_empty == 1) & (y.pred_empty == 0)).sum()))

    # ---------------------------------------------------------------- cohorts
    factors = ["CT phase", "scanner", "country", "slice thickness", "sex", "age", "tumour"]
    rows = []
    for f in factors:
        sub = coh[(coh.factor == f) & (~coh.small) & (coh.group != "(missing)")]
        groups = list(dict.fromkeys(sub[(sub.label == "pancreas") & (sub.metric == "dice")].group))
        ordr = {"≤ 1.25 mm": 0, "1.25–3 mm": 1, "> 3 mm": 2, "< 50": 0, "50–65": 1, "> 65": 2}
        groups.sort(key=lambda g: (ordr.get(g, 9), g))
        for i, g in enumerate(groups):
            vals = []
            for lab, met in (("pancreas", "dice"), ("pancreas", "nsd"), ("pancreatic_lesion", "dice")):
                r = sub[(sub.group == g) & (sub.label == lab) & (sub.metric == met)]
                vals.append(f3(r["mean"].iloc[0]) if len(r) else "--")
            n = int(sub[(sub.group == g) & (sub.label == "pancreas") & (sub.metric == "dice")].n.iloc[0])
            head = f"\\multirow{{{len(groups)}}}{{*}}{{{f[0].upper() + f[1:]}}}" if i == 0 else ""
            rows.append(f"{head} & {tex_group(g)} & {n} & " + " & ".join(vals) + " \\\\")
        ps = []
        for lab, met in (("pancreas", "dice"), ("pancreas", "nsd"), ("pancreatic_lesion", "dice")):
            t = coht[(coht.factor == f) & (coht.label == lab) & (coht.metric == met)]
            ps.append(ptex(float(t.p_adjusted.iloc[0])) if len(t) else "--")
        rows.append(" & \\emph{adjusted $p$} & & " + " & ".join(ps) + " \\\\ \\midrule")
    rows[-1] = rows[-1].replace(" \\midrule", "")
    table("t_cohorts", "llrrrr", "Factor & group & $n$ & pancreas Dice & pancreas NSD & lesion Dice", rows)
    pd_ = coh[(coh.label == "pancreas") & (coh.metric == "dice")].set_index("group")["mean"]
    for g, k in (("Venous", "Venous"), ("Non-contrast", "Noncon"), ("GE", "GE"), ("Siemens", "Siemens"),
                 ("≤ 1.25 mm", "Thin"), ("> 3 mm", "Thick")):
        cmd(f"coh{k}", f3(pd_[g]))
    cmd("cohPhaseP", ptex(float(coht[(coht.factor == "CT phase") & (coht.label == "pancreas") &
                                     (coht.metric == "dice")].p_adjusted.iloc[0])))
    cmd("nCohSig", int(coht.significant.sum()))
    cmd("nCohTests", len(coht))

    # ---------------------------------------------------------------- figures
    res = {MF: mf, TS: ts}
    organs = ["liver", "spleen", "kidney_left", "kidney_right", "stomach", "pancreas", "gall_bladder", "duodenum",
              "aorta", "postcava"]
    fig = P.metric_distribution(res, "dice", labels=organs, kind="box", figsize=(6.6, 2.9))
    with theme():
        ax = fig.axes[0]
        short = {"postcava": "IVC", "kidney_left": "Kidney\n(left)", "kidney_right": "Kidney\n(right)"}
        ax.set_xticklabels([short.get(s, NAME[s]) for s in organs], rotation=0, ha="center", fontsize=8)
        retitle(ax, "Per-case Dice on the 901 PanTS test CTs")
        ax.legend(ax.get_legend().legend_handles, [MF, TS], loc="lower left", ncols=2)
        ax.set_ylim(-0.02, 1.02)
    save(fig, "f_dice_dist")

    with theme():
        fig, axes = plt.subplots(1, 2, figsize=(6.6, 2.5), constrained_layout=True, sharey=True)
    for ax, s in zip(axes, ["spleen", "kidney_left"]):
        P.ecdf(res, "hd95", label=s, ax=ax)
        with theme():
            ax.set_xscale("symlog", linthresh=10)
            ax.set_xlim(0, 700)
            ax.axvline(50, color=INK["muted"], ls="--", lw=1)
            ax.text(52, 0.05, "50 mm", fontsize=7.5, color=INK["muted"])
            retitle(ax, f"HD95 of every case: {NAME[s].lower()}")
            ax.set_xlabel("HD95 [mm] (log scale above 10 mm)")
    with theme():
        axes[1].set_ylabel("")
        if axes[1].get_legend():
            axes[1].get_legend().remove()
        axes[0].legend(loc="center right")
    save(fig, "f_hd95_tail")

    fig = P.detection_by_size(mf, label="pancreatic_lesion", figsize=(3.3, 2.5))
    with theme():
        retitle(fig.axes[0], "Lesions found, by lesion size")
        for t in list(fig.axes[0].texts):  # counts are listed in the size table
            t.remove()
        fig.axes[0].tick_params(axis="x", labelsize=7.5)
    save(fig, "f_det_size")

    r = presence_detection(mf, "pancreatic_lesion")
    with theme():
        fig, ax = plt.subplots(figsize=(3.1, 2.5), constrained_layout=True)
        o = np.lexsort((r["tpr"], r["fpr"]))
        ax.plot(r["fpr"][o], r["tpr"][o], color=CATEGORICAL[0])
        ax.plot([0, 1], [0, 1], color=INK["muted"], ls="--", lw=1)
        ax.plot(1 - r["specificity"], r["sensitivity"], "o", color=CATEGORICAL[2], ms=6, zorder=5)
        ax.annotate(f"spec. {r['specificity']:.2f}, sens. {r['sensitivity']:.2f}",
                    (1 - r["specificity"], r["sensitivity"]), xytext=(10, -18), textcoords="offset points",
                    fontsize=7.5, color=INK["secondary"])
        ax.set_xlabel("1 − specificity (healthy patients flagged)")
        ax.set_ylabel("Sensitivity (sick found)")
        retitle(ax, f"Tumour or not? AUC {r['auc']:.3f}")
        ax.grid(True, axis="both")
    save(fig, "f_roc")

    fig = P.cohort_plot(coh[~coh.small], "dice", "pancreas", factor="CT phase", figsize=(3.2, 2.0))
    with theme():
        retitle(fig.axes[0], "Pancreas Dice by CT phase")
        for t in list(fig.axes[0].texts):  # the factor name is in the title
            t.remove()
    save(fig, "f_cohort_phase")

    sub = comp[comp.label.isin(ORGANS10) & comp.metric.isin(["dice", "nsd"])].copy()
    sub["label"] = sub["label"].map(lambda s: "IVC" if s == "postcava" else NAME[s].lower())
    fig = P.comparison_forest(sub, name_a="MF", name_b="TS", figsize=(5.2, 5.0))
    with theme():
        retitle(fig.axes[0], "MF minus TS, paired over the 901 cases")
    save(fig, "f_forest")

    # toy illustration for the metric section (a drawing, not data)
    toy_grid()
    toy_rank()

    (GEN / "macros.tex").write_text("% generated by make_report.py\n" + "\n".join(macros) + "\n")
    print(len(macros), "macros")


def toy_grid() -> None:
    """6x6 toy picture: reference 10 squares, prediction 9 squares, 8 shared (TP 8, FP 1, FN 2)."""
    ref = {(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3), (4, 2)}
    pred = {(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 2), (3, 3), (2, 4)}
    assert len(ref) == 10 and len(pred) == 9 and len(ref & pred) == 8
    with theme():
        fig, axes = plt.subplots(1, 3, figsize=(5.6, 1.75), constrained_layout=True)
        for ax, (title, mode) in zip(axes, [("Answer (reference)", "ref"), ("Your colouring (prediction)", "pred"),
                                             ("Compared", "both")]):
            for i in range(6):
                for j in range(6):
                    c = "white"
                    if mode == "ref" and (i, j) in ref:
                        c = PURPLE[300]
                    elif mode == "pred" and (i, j) in pred:
                        c = ERROR_COLORS["fp"]
                    elif mode == "both":
                        c = (ERROR_COLORS["tp"] if (i, j) in ref & pred else ERROR_COLORS["fn"] if (i, j) in ref
                             else ERROR_COLORS["fp"] if (i, j) in pred else "white")
                    ax.add_patch(plt.Rectangle((j, 5 - i), 1, 1, facecolor=c, edgecolor=INK["grid"], lw=0.8))
            ax.set_xlim(0, 6)
            ax.set_ylim(0, 6)
            ax.set_aspect("equal")
            ax.axis("off")
            ax.set_title(title, fontsize=8.5, loc="center")
        from matplotlib.patches import Patch

        axes[2].legend(handles=[Patch(color=ERROR_COLORS["tp"], label="TP = 8 (both)"),
                                Patch(color=ERROR_COLORS["fp"], label="FP = 1 (extra)"),
                                Patch(color=ERROR_COLORS["fn"], label="FN = 2 (missed)")],
                       loc="upper left", bbox_to_anchor=(1.0, 1.0), fontsize=7.5)
    save(fig, "f_toy_grid")


def toy_rank() -> None:
    """Toy example of the two ranking schemes: A = (.9, .9, .3), B = (.8, .8, .8)."""
    a, b = [0.9, 0.9, 0.3], [0.8, 0.8, 0.8]
    with theme():
        fig, ax = plt.subplots(figsize=(2.9, 1.95), constrained_layout=True)
        x = np.arange(3)
        ax.bar(x - 0.18, a, 0.34, color=CATEGORICAL[0], label=f"A (mean {np.mean(a):.2f})")
        ax.bar(x + 0.18, b, 0.34, color=CATEGORICAL[1], label=f"B (mean {np.mean(b):.2f})")
        ax.set_xticks(x)
        ax.set_xticklabels(["patient 1", "patient 2", "patient 3"])
        ax.set_ylim(0, 1.15)
        ax.set_ylabel("Dice")
        ax.legend(loc="upper center", ncols=2, fontsize=7.5, bbox_to_anchor=(0.5, 1.18))
        ax.tick_params(labelsize=8)
    save(fig, "f_toy_rank")


if __name__ == "__main__":
    main()
