"""Figures, tables and number macros for the R-Super MedFormer / PanTS report.

Every number in report.tex is written here from files produced by the benchmark
scripts; nothing is typed into the LaTeX by hand, except the numbers R-Super
reports on GitHub (REPORTED below, read off documents/demo_results.png).

Inputs
    outputs/eval/pants/medformer/                  per-case results (evaluate_models.py)
    outputs/eval/pants/medformer/rsuper_detection.csv
                                                   R-Super's own detection volume per case (rsuper_detection.py)
    outputs/eval/pants/totalseg/                   comparator
    outputs/eval/pants/report/                     test-set tables (benchmark_report.py)
    third_party/R-Super/rsuper_train/metadata_pants.csv   R-Super's patient-level ground truth
    generated/audit_pants_test.csv                 `segevalkit audit` of the test labels
    patched_cases.txt                              the 25 cases that needed the padding fix

    srun -p cscc-cpu-p ... python reports/rsuper_medformer/make_report.py   # reads NIfTI for Fig. 4
"""

from __future__ import annotations

import csv
import json
import subprocess
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

import segevalkit as sek  # noqa: E402
from segevalkit import plotting as P  # noqa: E402
from segevalkit import viz  # noqa: E402
from segevalkit.io import load_volume  # noqa: E402
from segevalkit.plotting.theme import CATEGORICAL, INK, theme  # noqa: E402
from segevalkit.stats import presence_detection  # noqa: E402

HERE = Path(__file__).resolve().parent
STORE = Path("/l/users/abhijit.das/SegEvalKit")
EVAL = STORE / "outputs/eval/pants"
REPORT = EVAL / "report"
RS = STORE / "third_party/R-Super"
PANTS = STORE / "data/raw/PanTS"
PRED = STORE / "outputs/predictions/medformer_pants/abdomenatlas/pants_pancreas_release"
GEN, FIG = HERE / "generated", HERE / "figures"
MF, TS = "MedFormer", "TotalSegmentator"

# R-Super GitHub, rsuper_train/Merlin_demo.md, figure documents/demo_results.png, "PanTS test" panel (%).
REPORTED = {"baseline": {"sens": 76, "spec": 91, "f1": 69},   # AbdomenAtlas/MedFormerPanTS (this checkpoint)
            "rsuper": {"sens": 80, "spec": 93, "f1": 74}}     # AbdomenAtlas/R-SuperPanTSMerlin (not run)
# Volume thresholds of calculate_sensitivity_specificity.py (voxels at 1 mm, i.e. mm^3).
RS_THRESHOLDS = ([i * 10 for i in range(1, 10)] + [i * 10 for i in range(10, 100)] +
                 [i * 100 for i in range(1, 100)] + [i * 1000 for i in range(1, 100)])

NAME = {"pancreas": "Pancreas", "pancreatic_lesion": "Pancreatic lesion", "liver": "Liver", "spleen": "Spleen",
        "kidney_left": "Kidney (L)", "kidney_right": "Kidney (R)", "stomach": "Stomach",
        "gall_bladder": "Gallbladder", "duodenum": "Duodenum", "colon": "Colon",
        "adrenal_gland_left": "Adrenal (L)", "adrenal_gland_right": "Adrenal (R)", "aorta": "Aorta",
        "postcava": "IVC", "superior_mesenteric_artery": "SMA", "veins": "Veins",
        "common_bile_duct": "Common bile duct"}
ORGANS10 = ["pancreas", "liver", "spleen", "kidney_left", "kidney_right", "stomach", "gall_bladder", "duodenum",
            "aorta", "postcava"]

macros: list[str] = []


def cmd(name: str, value) -> None:
    macros.append(f"\\newcommand{{\\{name}}}{{{value}}}")


def f3(v) -> str:
    if v is None or not np.isfinite(v):
        return "--"
    return "1.000" if v >= 0.9995 else f"{v:.3f}".replace("0.", ".", 1)


def f1(v) -> str:
    return "--" if v is None or not np.isfinite(v) else f"{v:.1f}"


def pct(v) -> str:
    return f"{100 * v:.0f}"


def ptex(p) -> str:
    if not np.isfinite(p):
        return "--"
    return "$<\\!10^{-3}$" if p < 1e-3 else f"{p:.3f}"


def tex_group(g: str) -> str:
    return (g.replace("%", "\\%").replace("–", "--").replace("≤ ", "$\\le$\\,").replace("> ", "$>$\\,")
            .replace("< ", "$<$\\,"))


def retitle(ax, text: str) -> None:
    ax.set_title("", loc="center")
    ax.set_title(text, loc="left", fontsize=9)


def save(fig, name: str) -> None:
    fig.savefig(FIG / f"{name}.pdf")
    plt.close(fig)
    print("figure", name)


def table(name: str, colspec: str, header: str, rows: list[str]) -> None:
    (GEN / f"{name}.tex").write_text(
        f"% generated by make_report.py\n\\begin{{tabular}}{{{colspec}}}\n\\toprule\n{header} \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


# ------------------------------------------------------------------ patient-level detection
def confusion(score, y, t):
    pos = score >= t
    tp, fp = int((pos & y).sum()), int((pos & ~y).sum())
    fn, tn = int((~pos & y).sum()), int((~pos & ~y).sum())
    return tp, fp, fn, tn


def op_point(score, y, thresholds, target_spec):
    """Threshold of the grid whose specificity is closest to ``target_spec`` (ties: higher sensitivity)."""
    best = None
    for t in thresholds:
        tp, fp, fn, tn = confusion(score, y, t)
        sens, spec = tp / (tp + fn), tn / (tn + fp)
        key = (abs(spec - target_spec), -sens)
        if best is None or key < best[0]:
            best = (key, t, sens, spec, 2 * tp / (2 * tp + fp + fn))
    return {"t": best[1], "sens": best[2], "spec": best[3], "f1": best[4]}


def roc_auc(score, y):
    thr = np.unique(np.concatenate([[-np.inf], score, [np.inf]]))
    tpr = np.array([(score[y] > t).mean() for t in thr])
    fpr = np.array([(score[~y] > t).mean() for t in thr])
    o = np.lexsort((tpr, fpr))
    return float(np.trapezoid(tpr[o], fpr[o])), fpr[o], tpr[o]


def boot(score, y, thresholds, target_spec, n=1000, seed=0):
    rng = np.random.default_rng(seed)
    out = []
    idx = np.arange(len(y))
    for _ in range(n):
        b = rng.choice(idx, len(idx), replace=True)
        out.append(op_point(score[b], y[b], thresholds, target_spec))
    d = pd.DataFrame(out)
    return {k: np.quantile(d[k], [0.025, 0.975]) for k in ("sens", "spec", "f1")}


def main() -> None:
    GEN.mkdir(exist_ok=True)
    FIG.mkdir(exist_ok=True)
    mf = sek.load_results(EVAL / "medformer")
    ts = sek.load_results(EVAL / "totalseg")
    mf.meta["name"], ts.meta["name"] = MF, TS
    wide, tsw = mf.wide(), ts.wide()
    macro = pd.read_csv(REPORT / "macro.csv")
    pooled = pd.read_csv(REPORT / "pooled.csv")
    comp = pd.read_csv(REPORT / f"compare_{MF}_vs_{TS}.csv")
    rank = pd.read_csv(REPORT / "ranking.csv")
    coh = pd.read_csv(REPORT / "cohorts_MedFormer.csv")
    coht = pd.read_csv(REPORT / "cohort_tests_MedFormer.csv")
    meta = json.loads((EVAL / "medformer/meta.json").read_text())
    audit = pd.read_csv(GEN / "audit_pants_test.csv")
    patched = [l.split(",")[0] for l in (HERE / "patched_cases.txt").read_text().splitlines() if l.startswith("PanTS")]
    mm = macro[macro.model == MF].set_index(["label", "metric"])
    tm = macro[macro.model == TS].set_index(["label", "metric"])
    pl = pooled[pooled.model == MF].set_index(["label", "metric"])

    # ---------------------------------------------------------------- provenance
    cmd("nCases", meta["n_cases"])
    cmd("sekVersion", meta["segevalkit_version"])
    cmd("evalDate", meta["created"][:10])
    cmd("nsdTol", f"{meta['config']['params']['nsd']['tolerance_mm']:g}")
    cmd("minLesionVox", meta["config"]["min_lesion_voxels"])
    rs = subprocess.run(["git", "-C", str(RS), "log", "-1", "--format=%h|%cs"], capture_output=True,
                        text=True).stdout.strip().split("|")
    cmd("rsuperCommit", rs[0])
    cmd("rsuperDate", rs[1])
    cmd("nPatched", len(patched))
    cmd("nAuditCases", audit.case_id.nunique())
    cmd("nAuditAorta", int((audit.structure == "aorta").sum()))
    cmd("nStructures", wide.label.nunique())

    # ---------------------------------------------------------------- reported vs reproduced
    lw = wide[wide.label == "pancreatic_lesion"].set_index("case_id")
    gt_rows = {r["BDMAP ID"].strip(): r for r in csv.DictReader(open(RS / "rsuper_train/metadata_pants.csv",
                                                                   encoding="utf-8-sig"))}
    cases = lw.index.to_list()
    y_rs = np.array([float(gt_rows[c]["number of pancreatic lesion instances"] or 0) >= 1 for c in cases])
    y_sek = (lw.ref_volume_ml > 0).to_numpy()
    cmd("nPos", int(y_rs.sum()))
    cmd("nNeg", int((~y_rs).sum()))
    cmd("nGTagree", int((y_rs == y_sek).sum()))
    det = pd.read_csv(EVAL / "medformer/rsuper_detection.csv").set_index("BDMAP_ID").loc[cases]
    v_rs = det["pancreatic tumor volume predicted"].to_numpy(float)       # mm^3 after R-Super's opening
    v_sek = lw.pred_volume_ml.to_numpy(float) * 1000.0                     # mm^3, no post-processing
    target = REPORTED["baseline"]["spec"] / 100
    rows_cmp, pts = [], {}
    for key, score, y, grid, lab in (
            ("A", v_rs, y_rs, RS_THRESHOLDS, "R-Super protocol (their volume, their thresholds)"),
            ("B", v_sek, y_sek, np.unique(v_sek), "SegEvalKit protocol (raw predicted volume)")):
        op = op_point(score, y, grid, target)
        ci = boot(score, y, grid, target)
        auc, fpr, tpr = roc_auc(score, y)
        pts[key] = (op, auc, fpr, tpr, ci)
        rows_cmp.append(f"{lab} & {pct(op['sens'])} {{\\scriptsize [{pct(ci['sens'][0])}, {pct(ci['sens'][1])}]}} & "
                        f"{pct(op['spec'])} & {pct(op['f1'])} {{\\scriptsize [{pct(ci['f1'][0])}, {pct(ci['f1'][1])}]}} & "
                        f"{auc:.3f} \\\\")
        for k, kn in (("sens", "Sens"), ("spec", "Spec"), ("f1", "Fone")):
            cmd(f"our{key}{kn}", pct(op[k]))
            cmd(f"our{key}{kn}Lo", pct(ci[k][0]))
            cmd(f"our{key}{kn}Hi", pct(ci[k][1]))
        cmd(f"our{key}AUC", f"{auc:.3f}")
        cmd(f"our{key}ThrML", f"{op['t'] / 1000:.2f}")
    r = REPORTED["baseline"]
    rows = [f"R-Super GitHub, this checkpoint\\textsuperscript{{a}} & {r['sens']} & {r['spec']} & {r['f1']} & -- \\\\",
            *rows_cmp,
            f"\\textcolor{{skmuted}}{{R-Super GitHub, R-Super model (not run)}} & \\textcolor{{skmuted}}{{{REPORTED['rsuper']['sens']}}} & "
            f"\\textcolor{{skmuted}}{{{REPORTED['rsuper']['spec']}}} & \\textcolor{{skmuted}}{{{REPORTED['rsuper']['f1']}}} & -- \\\\"]
    table("t_reported", "lrrrr", "Patient level, PanTS test (\\%) & Sensitivity & Specificity & F1 & AUC", rows)
    p90 = presence_detection(mf, "pancreatic_lesion")
    cmd("sensAtNinety", f"{p90['sensitivity']:.3f}")
    cmd("specAtNinety", f"{p90['specificity']:.3f}")
    cmd("thrAtNinety", f"{p90['threshold']:.2f}")
    cmd("reportedSens", r["sens"])
    cmd("reportedSpec", r["spec"])
    cmd("reportedFone", r["f1"])
    ciA = pts["A"][4]
    cmd("sensInCI", "within" if ciA["sens"][0] <= r["sens"] / 100 <= ciA["sens"][1] else "outside")
    cmd("fInCI", "within" if ciA["f1"][0] <= r["f1"] / 100 <= ciA["f1"][1] else "outside")
    # patched cases: do they matter for detection?
    pm = np.isin(np.array(cases), patched)
    cmd("nPatchedPos", int(y_rs[pm].sum()))

    with theme():
        fig, ax = plt.subplots(figsize=(3.25, 2.55), constrained_layout=True)
        for key, c, lab in (("A", CATEGORICAL[0], "R-Super protocol"), ("B", CATEGORICAL[1], "SegEvalKit protocol")):
            op, auc, fpr, tpr, _ = pts[key]
            ax.plot(fpr, tpr, color=c, lw=1.6, label=f"{lab} (AUC {auc:.3f})")
            ax.plot(1 - op["spec"], op["sens"], "o", color=c, ms=5, zorder=5)
        ax.plot(1 - r["spec"] / 100, r["sens"] / 100, "*", color=CATEGORICAL[2], ms=11, zorder=6,
                label="reported on GitHub")
        ax.plot([0, 1], [0, 1], color=INK["muted"], ls="--", lw=0.8)
        ax.set_xlim(-0.01, 0.5)
        ax.set_ylim(0.4, 1.0)
        ax.set_xlabel("1 $-$ specificity", fontsize=8)
        ax.set_ylabel("Sensitivity", fontsize=8)
        ax.tick_params(labelsize=7.5)
        ax.grid(True, axis="both")
        ax.legend(loc="lower right", fontsize=7)
        retitle(ax, "Patient level: tumour or not")
    save(fig, "f_roc")

    # ---------------------------------------------------------------- organ table (+ paired vs TS)
    order = [s for s in NAME if s in set(wide.label)]
    rows = []
    for s in order:
        cells = [f"{f3(mm.loc[(s, 'dice'), 'mean'])} / {f3(mm.loc[(s, 'dice'), 'median'])}",
                 f"{f3(mm.loc[(s, 'nsd'), 'mean'])} / {f3(mm.loc[(s, 'nsd'), 'median'])}",
                 f"{f1(mm.loc[(s, 'hd95'), 'mean'])} / {f1(mm.loc[(s, 'hd95'), 'median'])}"]
        if s in ORGANS10:
            c = comp[(comp.label == s) & (comp.metric == "dice")].iloc[0]
            cells += [f3(tm.loc[(s, "dice"), "mean"]), f"{pct(c.frac_a_better)}\\%"]
        else:
            cells += ["--", "--"]
        rows.append(f"{NAME[s]} & " + " & ".join(cells) + " \\\\")
    table("t_organs", "lrrrrr", "Structure & Dice mean / median & NSD mean / median & HD95 (mm) mean / median & "
          "TS Dice & MF better", rows)
    for s, k in (("pancreas", "Panc"), ("liver", "Liver"), ("spleen", "Spleen"), ("kidney_left", "KidL"),
                 ("duodenum", "Duod"), ("gall_bladder", "Gall"), ("common_bile_duct", "CBD")):
        cmd(f"mf{k}Dice", f3(mm.loc[(s, "dice"), "mean"]))
        cmd(f"mf{k}DiceMed", f3(mm.loc[(s, "dice"), "median"]))
        cmd(f"mf{k}NSD", f3(mm.loc[(s, "nsd"), "mean"]))
        cmd(f"mf{k}HD", f1(mm.loc[(s, "hd95"), "mean"]))
        cmd(f"mf{k}HDMed", f1(mm.loc[(s, "hd95"), "median"]))
    om = [mm.loc[(s, "dice"), "mean"] for s in order if s != "pancreatic_lesion"]
    cmd("mfNOrgansAbove", sum(v >= 0.85 for v in om))
    cmd("mfNOrgans", len(om))
    cmd("mfGallPooled", f3(pl.loc[("gall_bladder", "pooled_dice"), "value"]))
    d = comp[comp.metric == "dice"]
    cmd("fracDiceMin", pct(d.frac_a_better.min()))
    cmd("fracDiceMax", pct(d.frac_a_better.max()))
    cmd("fracSpleenDice", pct(d[d.label == "spleen"].frac_a_better.iloc[0]))
    cmd("tsSpleenDice", f3(tm.loc[("spleen", "dice"), "mean"]))
    cmd("tsSpleenHD", f1(tm.loc[("spleen", "hd95"), "mean"]))
    h = comp[comp.metric == "hd95"]
    cmd("nHDmeanWorse", int((h.mean_a > h.mean_b).sum()))
    cmd("nHDfracBetter", int((h.frac_a_better > 0.5).sum()))
    cmd("nCompSig", int(comp.significant.sum()))
    cmd("nComp", len(comp))
    flips = []
    for s, dd in rank[rank.scheme != "bootstrap"].groupby("structure", sort=False):
        wa = dd[dd.scheme == "aggregate-then-rank"].set_index("method")["rank"].idxmin()
        wr = dd[dd.scheme == "rank-then-aggregate"].set_index("method")["rank"].idxmin()
        if wa != wr:
            flips.append(NAME[s].lower().replace(" (l)", " (left)"))
    cmd("rankFlips", " and the ".join(flips) if flips else "none")
    cmd("tauMin", f"{rank[rank.scheme == 'bootstrap'].kendall_tau_median.min():.2f}")

    # HD95 tail decomposition
    for s, k in (("spleen", "Spleen"), ("kidney_left", "KidL")):
        x, y = wide[wide.label == s], tsw[tsw.label == s]
        t = x[x.hd95 > 50]
        both = t[(t.ref_empty == 0) & (t.pred_empty == 0)]
        cmd(f"tail{k}N", len(t))
        cmd(f"tail{k}Share", pct(t.hd95.sum() / x.hd95.sum()))
        cmd(f"tail{k}RefEmpty", int(((t.ref_empty == 1) & (t.pred_empty == 0)).sum()))
        cmd(f"tail{k}Both", len(both))
        cmd(f"tail{k}BothDice", f3(both.dice.median()))
        cmd(f"refEmpty{k}", int(x.ref_empty.sum()))
        cmd(f"tsPredOnEmpty{k}", int(((y.ref_empty == 1) & (y.pred_empty == 0)).sum()))
        cmd(f"tsTail{k}N", int((y.hd95 > 50).sum()))
        # HD95 without the empty-reference cases
        ok = x[x.ref_empty == 0]
        cmd(f"mf{k}HDnonEmpty", f1(ok.hd95.mean()))

    # ---------------------------------------------------------------- tumours
    les = mf.lesions
    lref = les[(les.kind == "ref") & (les.label == "pancreatic_lesion")]
    lpred = les[(les.kind == "pred_fp") & (les.label == "pancreatic_lesion")]  # unmatched predicted blobs
    pos, neg = lw[lw.ref_empty == 0], lw[lw.ref_empty == 1]
    cmd("nRefLesions", len(lref))
    cmd("nRefDetected", int(lref.detected.sum()))
    bins = [0, 0.5, 1, 5, 20, np.inf]
    names = ["$<$\\,0.5", "0.5--1", "1--5", "5--20", "$>$\\,20"]
    b = pd.cut(lref.volume_ml, bins=bins, labels=names, include_lowest=True, right=False)
    g = lref.groupby(b, observed=False)["detected"]
    cmd("detSmall", pct(g.mean()[names[0]]))
    cmd("nSmall", int(g.size()[names[0]]))
    cmd("detBig", pct(lref[lref.volume_ml >= 1].detected.mean()))
    lp = pl.loc["pancreatic_lesion"]
    rows = []
    for k, lab, fmt in (("pooled_lesion_sensitivity", "Tumours found (of \\nRefLesions)", "{:.2f}"),
                        ("pooled_lesion_precision", "Predicted tumours that are real", "{:.2f}"),
                        ("fp_lesions_per_scan", "False tumours per scan", "{:.2f}"),
                        ("pooled_dice", "Pooled tumour Dice", "{:.2f}")):
        rr = lp.loc[k]
        rows.append(f"{lab} & {fmt.format(rr.value)} {{\\scriptsize [{rr.ci_low:.2f}, {rr.ci_high:.2f}]}} \\\\")
    fp_neg, fp_pos = neg.false_positive_lesions.mean(), pos.false_positive_lesions.mean()
    rows += [f"False tumours per scan: tumour-free / tumour pat. & {fp_neg:.2f} / {fp_pos:.2f} \\\\",
             f"Per tumour patient: lesion precision & {f3(pos.lesion_precision.mean())} \\\\",
             f"Per tumour patient: tumour Dice (mean / median) & {f3(pos.dice.mean())} / {f3(pos.dice.median())} \\\\",
             f"Lesion probabilities: ECE / Brier & {mm.loc[('pancreatic_lesion', 'ece'), 'mean']:.3f} / "
             f"{mm.loc[('pancreatic_lesion', 'brier'), 'mean']:.3f} \\\\"]
    # detection curves: lesion scores = max lesion probability per predicted tumour (benchmarks/pants/lesion_scores.py)
    det = json.loads((REPORT / "detection_curves.json").read_text())["MedFormer"]
    pv = det["presence_volume"]
    rows += [f"FROC CPM (1/8--8 FP per scan) & {det['cpm']:.3f} "
             f"{{\\scriptsize [{det['cpm_ci'][0]:.2f}, {det['cpm_ci'][1]:.2f}]}} \\\\",
             f"Lesion-level average precision & {det['lesion_ap']:.3f} \\\\",
             f"Patient sens.\\ at spec.\\ 0.90, plain / localized & {pv['sensitivity']:.3f} / "
             f"{pv['sensitivity_localized']:.3f} \\\\",
             f"Patient AUC, plain / localized & {pv['auc']:.3f} / {pv['auc_localized']:.3f} \\\\"]
    cmd("cpm", f"{det['cpm']:.3f}")
    cmd("frocEighth", f"{det['sensitivity_at']['0.125']:.2f}")
    cmd("frocOne", f"{det['sensitivity_at']['1.0']:.2f}")
    cmd("lesAP", f"{det['lesion_ap']:.2f}")
    cmd("aucLoc", f"{pv['auc_localized']:.3f}")
    cmd("aucPlain", f"{pv['auc']:.3f}")
    cmd("sensLoc", f"{pv['sensitivity_localized']:.3f}")
    cmd("sensPlain", f"{pv['sensitivity']:.3f}")
    scored = sek.load_results(EVAL / "medformer_lesion_scores")
    scored.meta["name"] = "MedFormer"
    with theme():
        fig, axs = plt.subplots(1, 2, figsize=(6.4, 2.05), constrained_layout=True)
        P.froc_plot(scored, "pancreatic_lesion", n_boot=500, ax=axs[0])
        P.pr_plot(scored, "pancreatic_lesion", ax=axs[1])
        for ax, t in zip(axs, ("FROC (lesion level)", "Precision--recall (lesion level)")):
            retitle(ax, t.replace("--", "–"))
            ax.tick_params(labelsize=7.5)
            ax.xaxis.label.set_size(8)
            ax.yaxis.label.set_size(8)
            if ax.get_legend():
                for tx in ax.get_legend().get_texts():
                    tx.set_fontsize(7)
    save(fig, "f_froc_pr")
    table("t_tumour", "lr", "Tumour metric (95\\% CI) & MedFormer", rows)
    cmd("lesSens", f"{lp.loc['pooled_lesion_sensitivity'].value:.2f}")
    cmd("lesPrec", f"{lp.loc['pooled_lesion_precision'].value:.2f}")
    cmd("fpScan", f"{lp.loc['fp_lesions_per_scan'].value:.2f}")
    cmd("fpNeg", f"{fp_neg:.2f}")
    cmd("fpPos", f"{fp_pos:.2f}")
    cmd("posPrec", f3(pos.lesion_precision.mean()))
    cmd("posDice", f3(pos.dice.mean()))
    cmd("posDiceMed", f3(pos.dice.median()))
    cmd("nFPneg", int(lpred.merge(neg.reset_index()[["case_id"]], on="case_id").shape[0]))
    cmd("nFPall", len(lpred))
    fpv = lpred.merge(neg.reset_index()[["case_id"]], on="case_id").volume_ml
    cmd("fpNegMedML", f"{fpv.median():.2f}")
    cmd("fpNegSmallShare", pct((fpv < 0.5).mean()))

    fig = P.detection_by_size(mf, label="pancreatic_lesion", bins_ml=(0, 0.1, 0.5, 1, 5, 20, np.inf),
                              figsize=(3.25, 2.55))
    with theme():
        ax = fig.axes[0]
        retitle(ax, "Reference tumours found, by size")
        for t in list(ax.texts):
            t.remove()
        les_b = pd.cut(lref.volume_ml, bins=[0, 0.1, 0.5, 1, 5, 20, np.inf], include_lowest=True)
        for i, n in enumerate(lref.groupby(les_b, observed=False).size()):
            ax.text(i, 1.01, f"n={n}", ha="center", va="bottom", fontsize=7, color=INK["secondary"])
        ax.set_ylim(0, 1.12)
        ax.tick_params(labelsize=7.5)
        ax.set_xlabel("Reference tumour volume [mL]", fontsize=8)
        ax.set_ylabel("Fraction found", fontsize=8)
    save(fig, "f_det_size")

    # ---------------------------------------------------------------- organ figures
    res = {MF: mf, TS: ts}
    fig = P.metric_distribution(res, "dice", labels=ORGANS10, kind="box", figsize=(3.25, 2.55))
    with theme():
        ax = fig.axes[0]
        short = {"kidney_left": "Kid L", "kidney_right": "Kid R", "gall_bladder": "Gallbl.", "postcava": "IVC",
                 "pancreas": "Pancr.", "stomach": "Stom.", "duodenum": "Duod."}
        ax.set_xticklabels([short.get(s, NAME[s]) for s in ORGANS10], rotation=45, ha="right", fontsize=7)
        ax.tick_params(axis="y", labelsize=7.5)
        ax.set_ylabel("Dice", fontsize=8)
        retitle(ax, "Per-case Dice, 901 cases")
        ax.legend(ax.get_legend().legend_handles, ["MedFormer", "TotalSeg."], loc="lower left", ncols=2, fontsize=7)
        ax.set_ylim(-0.02, 1.02)
    save(fig, "f_dice")

    with theme():
        fig, ax = plt.subplots(figsize=(3.25, 2.55), constrained_layout=True)
    P.ecdf(res, "hd95", label="spleen", ax=ax)
    with theme():
        ax.set_xscale("symlog", linthresh=10)
        ax.set_xlim(0, 700)
        ax.axvline(50, color=INK["muted"], ls="--", lw=0.8)
        retitle(ax, "Spleen HD95, every case")
        ax.set_xlabel("HD95 [mm] (log above 10 mm)", fontsize=8)
        ax.set_ylabel("Fraction of cases ≤ x", fontsize=8)
        ax.tick_params(labelsize=7.5)
        ax.legend(["MedFormer", "TotalSeg."], loc="center right", fontsize=7)
    save(fig, "f_tail")

    # ---------------------------------------------------------------- cohorts
    rows = []
    for f in ("CT phase", "scanner", "slice thickness"):
        sub = coh[(coh.factor == f) & (~coh.small) & (coh.group != "(missing)")]
        groups = list(dict.fromkeys(sub[(sub.label == "pancreas") & (sub.metric == "dice")].group))
        ordr = {"≤ 1.25 mm": 0, "1.25–3 mm": 1, "> 3 mm": 2}
        groups.sort(key=lambda g: (ordr.get(g, 9), g))
        cells = []
        for g in groups:
            vals = []
            for lab, met in (("pancreas", "dice"), ("pancreas", "nsd"), ("pancreatic_lesion", "dice")):
                rr = sub[(sub.group == g) & (sub.label == lab) & (sub.metric == met)]
                vals.append(f3(rr["mean"].iloc[0]))
            n = int(sub[(sub.group == g) & (sub.label == "pancreas") & (sub.metric == "dice")].n.iloc[0])
            cells.append(f" & {tex_group(g)} ({n}) & " + " & ".join(vals) + " \\\\")
        cells[0] = f"{f[0].upper() + f[1:]}" + cells[0]
        ps = []
        for lab, met in (("pancreas", "dice"), ("pancreas", "nsd"), ("pancreatic_lesion", "dice")):
            t = coht[(coht.factor == f) & (coht.label == lab) & (coht.metric == met)]
            ps.append(ptex(float(t.p_adjusted.iloc[0])))
        rows += cells + [" & \\emph{adjusted $p$} & " + " & ".join(ps) + " \\\\ \\midrule"]
    rows[-1] = rows[-1].replace(" \\midrule", "")
    table("t_cohorts", "llrrr", "Factor & group ($n$) & Pancreas Dice & Pancreas NSD & Lesion Dice", rows)
    pdice = coh[(coh.label == "pancreas") & (coh.metric == "dice")].set_index("group")["mean"]
    for g, k in (("Venous", "Venous"), ("Non-contrast", "Noncon"), ("GE", "GE"), ("Siemens", "Siemens"),
                 ("≤ 1.25 mm", "Thin"), ("> 3 mm", "Thick")):
        cmd(f"coh{k}", f3(pdice[g]))
    cmd("nCohSig", int(coht.significant.sum()))
    cmd("nCohTests", len(coht))

    # ---------------------------------------------------------------- qualitative (three real cases)
    tp = pos[(pos.lesion_recall == 1) & (pos.ref_volume_ml.between(1, 20))]
    hit = (tp.dice - pos.dice.median()).abs().idxmin()
    small = lref[(lref.volume_ml < 0.5) & (~lref.detected.astype(bool))]
    miss_row = small.sort_values("volume_ml").iloc[-1]
    miss = miss_row.case_id
    negfp = neg[neg.pred_volume_ml > 0]
    fpc = (negfp.pred_volume_ml - negfp.pred_volume_ml.median()).abs().idxmin()
    picks = [(hit, f"Found, Dice {lw.loc[hit, 'dice']:.2f}\n({lw.loc[hit, 'ref_volume_ml']:.1f} mL tumour)"),
             (miss, f"Missed small tumour\n({miss_row.volume_ml:.3f} mL)"),
             (fpc, f"False tumour, tumour-free\n({lw.loc[fpc, 'pred_volume_ml']:.2f} mL predicted)")]
    with theme():
        fig, axes = plt.subplots(1, 3, figsize=(6.6, 2.35), constrained_layout=True)
    for ax, (c, title) in zip(axes, picks):
        ct = load_volume(PANTS / "ImageTe" / c / "ct.nii.gz", kind="image")
        ref = load_volume(PANTS / "LabelTe" / c / "segmentations/pancreatic_lesion.nii.gz").data > 0
        pr = load_volume(PRED / c / "predictions/pancreatic_lesion.nii.gz").data > 0
        rc, _ = viz.overlay.to_canonical(ref, ct.affine)
        pc, _ = viz.overlay.to_canonical(pr, ct.affine)
        idx = viz.overlay.pick_slice(None, rc if rc.any() else pc, "axial", "ref")  # largest tumour section
        viz.error_overlay(ct.data, pr, ref, affine=ct.affine, index=idx, ax=ax, legend=False)
        with theme():
            ax.set_title(f"{c.replace('PanTS_0000', 'case ')}: {title}", fontsize=7.5, loc="left")
            (x0, x1), (y1, y0) = ax.get_xlim(), ax.get_ylim()
            cx, cy, half = (x0 + x1) / 2, (y0 + y1) / 2, max(x1 - x0, y1 - y0, 60) / 2 + 10
            ax.set_xlim(cx - half, cx + half)
            ax.set_ylim(cy + half, cy - half)
    viz.error_legend(fig, window="abdomen")
    save(fig, "f_cases")
    for i, (c, _) in enumerate(picks):
        cmd(f"case{'ABC'[i]}", c)

    (GEN / "macros.tex").write_text("% generated by make_report.py\n" + "\n".join(macros) + "\n")
    print(len(macros), "macros")


if __name__ == "__main__":
    main()
